version: "3.8"

services:
  backend:
    build:
      - context: ./backend
      - dockerfile: Dockerfile
    command: uvicorn app.main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000

  frontend:
    build:
      - context: ./frontend
      - target: development
      - dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

networks:
  app:
    driver: bridge
