"""delete cart model, add cart field in user model

Revision ID: 17e5139efb47
Revises: 7ef6a84f10c7
Create Date: 2023-06-23 06:26:19.678007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e5139efb47'
down_revision = '7ef6a84f10c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_carts_id', table_name='carts')
    op.drop_table('carts')
    op.drop_constraint('products_cart_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'cart_id')
    op.add_column('users', sa.Column('cart', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cart')
    op.add_column('products', sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_cart_id_fkey', 'products', 'carts', ['cart_id'], ['id'])
    op.create_table('carts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='carts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='carts_pkey')
    )
    op.create_index('ix_carts_id', 'carts', ['id'], unique=False)
    # ### end Alembic commands ###
