"""add dog age and fix writting card_id to cart_id

Revision ID: 7ef6a84f10c7
Revises: 3cd067ff5611
Create Date: 2023-06-23 03:34:59.110077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef6a84f10c7'
down_revision = '3cd067ff5611'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('age', sa.String(), nullable=True))
    op.add_column('products', sa.Column('cart_id', sa.Integer(), nullable=True))
    op.drop_constraint('products_card_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'carts', ['cart_id'], ['id'])
    op.drop_column('products', 'card_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_card_id_fkey', 'products', 'carts', ['card_id'], ['id'])
    op.drop_column('products', 'cart_id')
    op.drop_column('products', 'age')
    # ### end Alembic commands ###
