"""add products_in_cart in users remove in_cart_user_id in products

Revision ID: 8827ecb2fa31
Revises: acd23b946bd9
Create Date: 2023-06-23 11:17:30.581885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8827ecb2fa31'
down_revision = 'acd23b946bd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'in_cart_user_id')
    op.add_column('users', sa.Column('products_in_cart', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'products_in_cart')
    op.add_column('products', sa.Column('in_cart_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
