"""Add role column in users table

Revision ID: 90e9d5091c63
Revises: ccc12cf3a3d0
Create Date: 2023-06-17 02:16:03.753246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e9d5091c63'
down_revision = 'ccc12cf3a3d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_price', table_name='products')
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=True))
    op.drop_index('ix_users_phone', table_name='users')
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.drop_column('users', 'role')
    op.create_index('ix_products_price', 'products', ['price'], unique=False)
    # ### end Alembic commands ###
