"""Add image_uri column to users, products tables

Revision ID: 954242fbf405
Revises: 59b6362f8de9
Create Date: 2023-06-14 02:53:09.119805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954242fbf405'
down_revision = '59b6362f8de9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_uri', sa.String(), nullable=True))
    op.add_column('users', sa.Column('image_uri', sa.String(), nullable=True))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'image_uri')
    op.drop_column('products', 'image_uri')
    # ### end Alembic commands ###
