"""add remove fields from users, products model

Revision ID: acd23b946bd9
Revises: 17e5139efb47
Create Date: 2023-06-23 07:55:34.171115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd23b946bd9'
down_revision = '17e5139efb47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
