"""Change to id to string type and a bit others

Revision ID: ccc12cf3a3d0
Revises: 954242fbf405
Create Date: 2023-06-16 00:52:03.323851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ccc12cf3a3d0"
down_revision = "954242fbf405"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pass
    op.alter_column(
        "users",
        "id",
        type_=sa.String(),
        postgresql_using="id::string",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
